CREATE TABLE authentication_rate_limits (
  scope text NOT NULL,
  subject_digest text NOT NULL CHECK (subject_digest ~ '^[a-f0-9]{64}$'),
  window_started_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  attempts integer NOT NULL DEFAULT 1 CHECK (attempts > 0),
  PRIMARY KEY (scope, subject_digest)
);

CREATE TABLE installation_audit_records (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type text NOT NULL CHECK (event_type ~ '^[a-z][a-z0-9_.]{2,127}$'),
  event_version integer NOT NULL DEFAULT 1 CHECK (event_version = 1),
  actor_type text NOT NULL CHECK (actor_type IN ('anonymous', 'host', 'operator', 'service')),
  actor_id uuid,
  target_type text NOT NULL CHECK (target_type ~ '^[a-z][a-z0-9_]{1,63}$'),
  target_id uuid,
  correlation_id uuid NOT NULL,
  causation_id uuid,
  outcome text NOT NULL CHECK (outcome IN ('denied', 'succeeded')),
  denial_reason text CHECK (denial_reason IS NULL OR char_length(denial_reason) <= 128),
  facts jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (
    jsonb_typeof(facts) = 'object'
    AND octet_length(facts::text) <= 4096
  ),
  occurred_at timestamptz NOT NULL,
  prior_record_hash text CHECK (prior_record_hash ~ '^[a-f0-9]{64}$'),
  record_hash text NOT NULL UNIQUE CHECK (record_hash ~ '^[a-f0-9]{64}$'),
  CHECK (
    (outcome = 'denied' AND denial_reason IS NOT NULL)
    OR (outcome = 'succeeded' AND denial_reason IS NULL)
  )
);

CREATE INDEX installation_audit_correlation_idx
ON installation_audit_records (correlation_id);

CREATE FUNCTION reject_installation_audit_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'Installation Audit is append-only';
END;
$$;

CREATE TRIGGER installation_audit_append_only
BEFORE UPDATE OR DELETE ON installation_audit_records
FOR EACH ROW
EXECUTE FUNCTION reject_installation_audit_mutation();
