import { useEffect, useRef, useState } from "react";
import type { FeaturePlanVersion } from "@kestrel/contracts";
import { fetchFeaturePlanVersion } from "./api.js";
import { planningRequestError } from "./FeatureNavigation.js";
import { ProjectDocumentContents } from "./PlanningDetails.js";
import { Button } from "./components/ui/button.js";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogTitle,
  DialogTrigger,
} from "./components/ui/dialog.js";

function ProposedDocumentContents({ version }: { version: FeaturePlanVersion }) {
  const documents = version.document.proposedDocuments ?? [];
  return (
    <div className="space-y-4">
      <p>
        {version.author === "assistant" ? "Generated by Kestrel" : "Saved by you"} with plan version{" "}
        {version.version}. Applying these proposals belongs to their owning Work Items after
        approval.
      </p>
      {documents.length === 0 ? (
        <p>This plan version has no proposed Project documents.</p>
      ) : (
        documents.map((document) => (
          <section
            key={document.key}
            className="space-y-2"
            aria-label={`Proposed ${document.path}`}
          >
            <h3>
              {document.kind === "adr" ? "ADR" : "Glossary"} · {document.key}
            </h3>
            <p>
              {document.pathIsProvisional ? "Provisional path" : "Proposed path"}:{" "}
              <code>{document.path}</code>
            </p>
            <p>Owning Work Item: {document.workItemKey}</p>
            <pre
              tabIndex={0}
              className="plan-artifact"
              aria-label={`Proposed contents of ${document.path}`}
            >
              {document.markdown}
            </pre>
          </section>
        ))
      )}
    </div>
  );
}

function usePlanDocumentView() {
  const [sources, setSources] = useState(false);
  const sourceButton = useRef<HTMLButtonElement>(null);
  const backButton = useRef<HTMLButtonElement>(null);
  const focusRequested = useRef(false);
  const changeView = (next: boolean) => {
    focusRequested.current = true;
    setSources(next);
  };
  useEffect(() => {
    if (!focusRequested.current) return;
    focusRequested.current = false;
    (sources ? backButton : sourceButton).current?.focus();
  }, [sources]);
  return {
    sources,
    sourceButton,
    backButton,
    changeView,
    reset() {
      focusRequested.current = false;
      setSources(false);
    },
    onEscapeKeyDown: (event: KeyboardEvent) => {
      if (!sources) return;
      event.preventDefault();
      changeView(false);
    },
  };
}

function PlanDocumentContents({
  version,
  view,
}: {
  version: FeaturePlanVersion;
  view: ReturnType<typeof usePlanDocumentView>;
}) {
  return view.sources ? (
    <>
      <Button variant="outline" ref={view.backButton} onClick={() => view.changeView(false)}>
        Back to proposed documents
      </Button>
      <ProjectDocumentContents
        context={version.sourceContext}
        emptyMessage="No source snapshot was recorded for this plan version."
      />
    </>
  ) : (
    <>
      <Button variant="outline" ref={view.sourceButton} onClick={() => view.changeView(true)}>
        Sources supplied for this plan
      </Button>
      <ProposedDocumentContents version={version} />
    </>
  );
}

export function ProposedDocumentsInspector({ version }: { version: FeaturePlanVersion }) {
  const view = usePlanDocumentView();
  return (
    <Dialog
      onOpenChange={(open) => {
        if (!open) view.reset();
      }}
    >
      <DialogTrigger asChild>
        <Button variant="outline">Proposed documents</Button>
      </DialogTrigger>
      <DialogContent
        onEscapeKeyDown={view.onEscapeKeyDown}
        className="planning-documents-dialog max-h-[85dvh] overflow-y-auto sm:max-w-4xl"
      >
        <DialogTitle>
          {view.sources
            ? "Sources supplied for this plan"
            : `Proposed documents · version ${String(version.version)}`}
        </DialogTitle>
        <DialogDescription>
          {view.sources
            ? "The committed Project documents and Skills supplied when this plan was created."
            : "Draft Markdown retained with this immutable plan, separate from committed Project documents."}
        </DialogDescription>
        <PlanDocumentContents version={version} view={view} />
      </DialogContent>
    </Dialog>
  );
}

export function GeneratedPlanDocuments({
  projectId,
  featureId,
  versionNumber,
  online,
  onAuthenticationError,
  loadVersion = fetchFeaturePlanVersion,
}: {
  projectId: string;
  featureId: string;
  versionNumber: number;
  online: boolean;
  onAuthenticationError: (error: unknown) => boolean;
  loadVersion?: typeof fetchFeaturePlanVersion;
}) {
  const [open, setOpen] = useState(false);
  const view = usePlanDocumentView();
  const [version, setVersion] = useState<FeaturePlanVersion | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [attempt, setAttempt] = useState(0);
  useEffect(() => {
    if (!open || !online) return;
    const controller = new AbortController();
    setVersion(null);
    setError(null);
    void loadVersion(projectId, featureId, versionNumber, controller.signal)
      .then((result) => {
        if (controller.signal.aborted) return;
        if (result.featureId !== featureId || result.version !== versionNumber)
          throw new Error("Unexpected plan version");
        setVersion(result);
      })
      .catch((failure: unknown) => {
        if (!controller.signal.aborted && !onAuthenticationError(failure))
          setError(planningRequestError(failure, "This plan version could not be loaded."));
      });
    return () => controller.abort();
  }, [
    open,
    online,
    projectId,
    featureId,
    versionNumber,
    loadVersion,
    onAuthenticationError,
    attempt,
  ]);
  return (
    <Dialog
      open={open}
      onOpenChange={(next) => {
        setOpen(next);
        if (!next) view.reset();
      }}
    >
      <DialogTrigger asChild>
        <Button variant="outline" size="sm" disabled={!online}>
          Inspect plan {versionNumber} documents
        </Button>
      </DialogTrigger>
      <DialogContent
        onEscapeKeyDown={view.onEscapeKeyDown}
        className="planning-documents-dialog max-h-[85dvh] overflow-y-auto sm:max-w-4xl"
      >
        <DialogTitle>
          {view.sources
            ? "Sources supplied for this plan"
            : `Proposed documents · version ${String(versionNumber)}`}
        </DialogTitle>
        <DialogDescription>
          {view.sources
            ? "The committed Project documents and Skills supplied when this plan was created."
            : "The exact plan generated by this reply. Later drafts do not change its documents or sources."}
        </DialogDescription>
        {error !== null ? (
          <div role="alert">
            <p>{error}</p>
            <Button
              variant="outline"
              disabled={!online}
              onClick={() => setAttempt((value) => value + 1)}
            >
              Retry loading documents
            </Button>
          </div>
        ) : version === null ? (
          <p role="status">Loading proposed documents…</p>
        ) : (
          <PlanDocumentContents version={version} view={view} />
        )}
      </DialogContent>
    </Dialog>
  );
}
