import { useEffect, useState } from "react";
import type { FeaturePlanVersion } from "@kestrel/contracts";
import { fetchFeaturePlanVersion } from "./api.js";
import { planningRequestError } from "./FeatureNavigation.js";
import { DocumentInspector } from "./PlanningDetails.js";
import { Button } from "./components/ui/button.js";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogTitle,
  DialogTrigger,
} from "./components/ui/dialog.js";

function ProposedDocumentContents({ version }: { version: FeaturePlanVersion }) {
  const documents = version.document.proposedDocuments ?? [];
  return (
    <div className="space-y-4">
      <p>
        {version.author === "assistant" ? "Generated by Kestrel" : "Saved by you"} with plan version{" "}
        {version.version}. Applying these proposals belongs to their owning Work Items after
        approval.
      </p>
      <DocumentInspector
        context={version.sourceContext}
        label="Sources supplied for this plan"
        emptyMessage="No source snapshot was recorded for this plan version."
      />
      {documents.length === 0 ? (
        <p>This plan version has no proposed Project documents.</p>
      ) : (
        documents.map((document) => (
          <section
            key={document.key}
            className="space-y-2"
            aria-label={`Proposed ${document.path}`}
          >
            <h3>
              {document.kind === "adr" ? "ADR" : "Glossary"} · {document.key}
            </h3>
            <p>
              {document.pathIsProvisional ? "Provisional path" : "Proposed path"}:{" "}
              <code>{document.path}</code>
            </p>
            <p>Owning Work Item: {document.workItemKey}</p>
            <pre
              tabIndex={0}
              className="plan-artifact"
              aria-label={`Proposed contents of ${document.path}`}
            >
              {document.markdown}
            </pre>
          </section>
        ))
      )}
    </div>
  );
}

export function ProposedDocumentsInspector({ version }: { version: FeaturePlanVersion }) {
  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button variant="outline">Proposed documents</Button>
      </DialogTrigger>
      <DialogContent className="planning-documents-dialog max-h-[85dvh] overflow-y-auto sm:max-w-4xl">
        <DialogTitle>Proposed documents · version {version.version}</DialogTitle>
        <DialogDescription>
          Draft Markdown retained with this immutable plan, separate from committed Project
          documents.
        </DialogDescription>
        <ProposedDocumentContents version={version} />
      </DialogContent>
    </Dialog>
  );
}

export function GeneratedPlanDocuments({
  projectId,
  featureId,
  versionNumber,
  online,
  onAuthenticationError,
  loadVersion = fetchFeaturePlanVersion,
}: {
  projectId: string;
  featureId: string;
  versionNumber: number;
  online: boolean;
  onAuthenticationError: (error: unknown) => boolean;
  loadVersion?: typeof fetchFeaturePlanVersion;
}) {
  const [open, setOpen] = useState(false);
  const [version, setVersion] = useState<FeaturePlanVersion | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [attempt, setAttempt] = useState(0);
  useEffect(() => {
    if (!open || !online) return;
    const controller = new AbortController();
    setVersion(null);
    setError(null);
    void loadVersion(projectId, featureId, versionNumber, controller.signal)
      .then((result) => {
        if (controller.signal.aborted) return;
        if (result.featureId !== featureId || result.version !== versionNumber)
          throw new Error("Unexpected plan version");
        setVersion(result);
      })
      .catch((failure: unknown) => {
        if (!controller.signal.aborted && !onAuthenticationError(failure))
          setError(planningRequestError(failure, "This plan version could not be loaded."));
      });
    return () => controller.abort();
  }, [
    open,
    online,
    projectId,
    featureId,
    versionNumber,
    loadVersion,
    onAuthenticationError,
    attempt,
  ]);
  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button variant="outline" size="sm" disabled={!online}>
          Inspect plan {versionNumber} documents
        </Button>
      </DialogTrigger>
      <DialogContent className="planning-documents-dialog max-h-[85dvh] overflow-y-auto sm:max-w-4xl">
        <DialogTitle>Proposed documents · version {versionNumber}</DialogTitle>
        <DialogDescription>
          The exact plan generated by this reply. Later drafts do not change its documents or
          sources.
        </DialogDescription>
        {error !== null ? (
          <div role="alert">
            <p>{error}</p>
            <Button
              variant="outline"
              disabled={!online}
              onClick={() => setAttempt((value) => value + 1)}
            >
              Retry loading documents
            </Button>
          </div>
        ) : version === null ? (
          <p role="status">Loading proposed documents…</p>
        ) : (
          <ProposedDocumentContents version={version} />
        )}
      </DialogContent>
    </Dialog>
  );
}
